snippets:
# snippet and keyword abbrev
- name: git status
  keyword: gs
  snippet: git status --short --branch

# snippet with placeholder
- name: git commit message
  keyword: gcim
  snippet: git commit -m '{{commit_message}}'

- name: "null"
  keyword: "null"
  snippet: ">/dev/null 2>&1"
  enableMiddleOfLine: true # auto expand in middle of line

completions:
- name: kill
  patterns: 
    - "^kill( -9)? $"
  sourceCommand: "ps -ef | sed 1d"
  options:
    --multi: true
    --prompt: "'Kill Process> '"
  callback: "awk '{print $2}'"
